name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm colorama pytest
    
    - name: Run tests
      run: |
        pytest test_main.py -v
    
    - name: Run main script
      run: python main.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm colorama
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 34.101.137.191 >> ~/.ssh/known_hosts
    
    - name: Deploy to GCP
      run: |
        scp -i ~/.ssh/id_rsa -r ./* mikahoy045@34.101.137.191:/home/mikahoy045/app
        ssh -i ~/.ssh/id_rsa mikahoy045@34.101.137.191 'cd /home/mikahoy045/app && python main.py'
